@baseUrl = http://localhost:3000

POST {{baseUrl}}/api/auth/customer/signup
Content-Type: application/json

{
  "email": "fullmetal2334@gmail.com",
  "password": "12345678"
}

###
POST {{baseUrl}}/api/auth/customer/verify-otp
Content-Type: application/json

{
  "email": "fullmetal2336@gmail.com",
  "otp": "viTgwI"
}
###
# @name customerlogin
POST {{baseUrl}}/api/auth/customer/login
Content-Type: application/json

{
  "email": "fullmetal2336@gmail.com",
  "password": "12345678"
}

###
POST {{baseUrl}}/api/auth/print-agent/signup
Content-Type: application/json

{
  "email": "fullmetal2336@gmail.com",
  "password": "12345678",
  "full_name": "fullmetal",
  "business_name": "fullmetal",
  "business_type": "Cafe"
}

###
POST {{baseUrl}}/api/auth/print-agent/verify-otp
Content-Type: application/json

{
  "email": "fullmetal2336@gmail.com",
  "otp": "1eLYUj"
}

###
# @name printlogin
POST {{baseUrl}}/api/auth/print-agent/login
Content-Type: application/json

{
  "email": "fullmetal2336@gmail.com",
  "password": "12345678"
}

